#!/bin/sh



for CPPFILE in *.cpp ; do

  CPPNAME=$(echo $CPPFILE| cut -d'.' -f 1); #remove extension
  clang++ -std=c++11 -stdlib=libc++ -Wall -Wextra $CPPFILE -o "${CPPNAME}.out";

  printf "${CPPNAME}: " >> progress.txt;
  ./"${CPPNAME}.out" >> progress.txt;
  printf "\n" >> progress.txt;

done

cat progress.txt;
